In [1]:
import requests
import numpy as np
import pandas as pd
import string as st
import os
import csv
import re
import random
from sklearn.linear_model import LinearRegression

from sklearn.feature_selection import RFE

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
path1 = 'DataFinal_clean.csv'

X = pd.read_csv(path1,encoding= "ISO-8859-1", low_memory=False)

In [3]:

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import f_regression
from __future__ import division

In [4]:
X.head(10)

,ptid,Nbabies,pregravidbmi,gravida,para,term,preterm,abort,tab,sab,...,payor_MCAIDHMO,payor_MCARE,payor_MCARE AD,payor_MG CARE,payor_OTHER,payor_SELF PAY,payor_SO HLTH,payor_TRICARE,payor_UNITED,gestage
0,540,0.0,0.048746,0.066667,0.083333,0.000000,0.2,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,39
1,567,0.0,0.030289,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,39
2,637,0.0,0.050639,0.066667,0.083333,0.083333,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,39
3,749,0.0,0.019877,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,34
4,780,0.0,0.050639,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,38
5,956,0.0,0.044487,0.066667,0.000000,0.000000,0.0,0.1,0.0,0.1,...,0,0,0,0,0,0,0,0,0,37
6,1128,0.0,0.086133,0.133333,0.083333,0.083333,0.0,0.1,0.0,0.0,...,1,0,0,0,0,0,0,0,0,39
7,1568,0.0,0.026029,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,37
8,1900,0.0,0.107430,0.466667,0.333333,0.250000,0.2,0.2,0.0,0.2,...,0,1,0,0,0,0,0,0,0,39
9,2852,0.0,0.050639,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,39

In [5]:
X.isnull().sum().sum()

0

In [6]:
target = X['gestage']
target = pd.to_numeric(target)

In [7]:
newset = X.drop(['gestage'], axis=1)
X_new = SelectKBest(f_regression, k=30).fit_transform(newset, target)

/apps/software/standard/core/anaconda3/4.4.0/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:279: RuntimeWarning: invalid value encountered in true_divide
  corr /= row_norms(X.T)
/apps/software/standard/core/anaconda3/4.4.0/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/apps/software/standard/core/anaconda3/4.4.0/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/apps/software/standard/core/anaconda3/4.4.0/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1818: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

In [8]:
X_new = pd.DataFrame(X_new)

In [16]:
newset.drop(newset.iloc[:, 12:4097], inplace=True, axis=1)

In [17]:
newset.head(10)

,ptid,Nbabies,pregravidbmi,gravida,para,term,preterm,abort,tab,sab,...,payor_MCAID OS,payor_MCAIDHMO,payor_MCARE,payor_MCARE AD,payor_MG CARE,payor_OTHER,payor_SELF PAY,payor_SO HLTH,payor_TRICARE,payor_UNITED
0,540,0.0,0.048746,0.066667,0.083333,0.000000,0.2,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
1,567,0.0,0.030289,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,637,0.0,0.050639,0.066667,0.083333,0.083333,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,749,0.0,0.019877,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
4,780,0.0,0.050639,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,956,0.0,0.044487,0.066667,0.000000,0.000000,0.0,0.1,0.0,0.1,...,0,0,0,0,0,0,0,0,0,0
6,1128,0.0,0.086133,0.133333,0.083333,0.083333,0.0,0.1,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
7,1568,0.0,0.026029,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8,1900,0.0,0.107430,0.466667,0.333333,0.250000,0.2,0.2,0.0,0.2,...,0,0,1,0,0,0,0,0,0,0
9,2852,0.0,0.050639,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
lr = LinearRegression()
lr.fit(newset, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
rfe = RFE(lr, 1)

In [20]:
rfe = rfe.fit(newset, target)

In [21]:
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]
[42  2 31 10 28 29  3  9 33 11 12 19  1 14 18 41 30  6 21 40 22 36  4 32 34
 35  8 23 26 39 16 38  5 17 25 15 13  7 37 20 24 27]

In [22]:
columnlist = list(newset.columns)

In [23]:
ranks = list(rfe.ranking_)

In [24]:
columnlist = pd.DataFrame(columnlist)
columnlist["ranks"] = ranks
topfeatures = columnlist.sort_values("ranks")
topfeatures = topfeatures.rename(index=str, columns={0: "features"})
topfeatures = topfeatures.reset_index()
topfeatures.head()

  index        features  ranks
0    12           Z99.2      1
1     1         Nbabies      2
2     6         preterm      3
3    22     ethnicity_0      4
4    32  payor_MCAID OS      5

In [25]:
top30 = topfeatures.features[0:30]
top30

0              Z99.2
1            Nbabies
2            preterm
3        ethnicity_0
4     payor_MCAID OS
5             race_I
6        payor_OTHER
7        ethnicity_U
8              abort
9            gravida
10               sab
11           ectopic
12     payor_MG CARE
13            Z99.81
14    payor_MCARE AD
15        payor_COMM
16    payor_MCAIDHMO
17            race_A
18               age
19     payor_SO HLTH
20            race_N
21            race_U
22       payor_AETNA
23     payor_TRICARE
24       payor_MCARE
25      payor_BCROSS
26      payor_UNITED
27              para
28              term
29            race_H
Name: features, dtype: object

In [26]:
top20 = topfeatures.features[0:20]
top10 = topfeatures.features[0:10]
top10

0             Z99.2
1           Nbabies
2           preterm
3       ethnicity_0
4    payor_MCAID OS
5            race_I
6       payor_OTHER
7       ethnicity_U
8             abort
9           gravida
Name: features, dtype: object